services:
  mariadb:
    container_name: mariadb
    build:
      context: requirements/mariadb
    volumes:
      - mdb:/var/lib/mysql
    restart: on-failure
    env_file: .env
    networks: 
      - inception_net

  wordpress:
    container_name: wordpress
    build:
      context: requirements/wordpress
    depends_on:
      - mariadb
    volumes: 
      - wp:/var/www/html
    networks: 
      - inception_net
    restart: on-failure
    env_file: .env

  nginx:
    container_name: nginx
    build:
      context: requirements/nginx
    ports: 
      - 80:80
      # - 443:443
    volumes: 
      - wp:/var/www/html
    # restart: always
    networks: 
      - inception_net
    depends_on:
      - wordpress
      

volumes:
  mdb:
    driver: local
    # driver_opts:
    #   type: none
      # device: /home/mlumibao/data/mysql
      # o: bind
  wp:
    driver: local
    # driver_opts:
    #   type: none
    #   device: /home/mlumibao/data/wordpress
    #   o: bind

networks:
    inception_net:
        name: inception_net
        driver: bridge
